name: Classify Changed JSON

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
    branches:
      - main
      - workflows_LLM

jobs:
  classify-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          ignore_whitespace: true
          base_sha: ${{ github.event.pull_request.base.sha }}

      - name: Find changed JSON files
        id: find-json
        run: |
          FILES="${{ steps.changed-files.outputs.all_changed_files }}"
          FILES=$(echo "$FILES" | tr -s ' ' | sed 's/^ *//;s/ *$//')

          read -ra FILE_ARRAY <<< "$FILES"
          COUNT=${#FILE_ARRAY[@]}

          echo "🔍 Found $COUNT changed file(s)"
          for f in "${FILE_ARRAY[@]}"; do
            echo "  - $f"
          done

          if [[ "$COUNT" -ne 2 ]]; then
            echo "❌ PR must change exactly two files"
            exit 1
          fi

          # Check that at least one file is a JSON file
          JSON_FILES=()
          for FILE in "${FILE_ARRAY[@]}"; do
            if [[ "${FILE}" == *.json ]]; then
              JSON_FILES+=("$FILE")
            fi
          done

          if [[ ${#JSON_FILES[@]} -eq 0 ]]; then
            echo "❌ At least one file must be a .json file"
            exit 1
          fi

          echo "✅ Found ${#JSON_FILES[@]} JSON file(s) out of $COUNT total files"
          # Use the first JSON file for classification
          echo "json_file_path=${JSON_FILES[0]}" >> "$GITHUB_OUTPUT"

      - name: Show JSON content
        run: |
          echo "📂 Printing JSON file: ${{ steps.find-json.outputs.json_file_path }}"
          cat "${{ steps.find-json.outputs.json_file_path }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run classification
        run: |
          python classify.py "${{ steps.find-json.outputs.json_file_path }}" > result.txt
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Decide pass/fail
        run: |
          echo "=== Classification Output ==="
          cat result.txt

          if grep -q "✅ All checks passed" result.txt; then
            echo "✅ Workflow passed"
          else
            echo "❌ Workflow failed"
            exit 1
          fi
