name: Check if valid label exists

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
    branches:
      - main
      - automate_action_check

jobs:
  check-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check for required labels
        id: label_check
        uses: actions/github-script@v7
        with:
          script: |
            const requiredLabels = ["medium", "expert", "hard", "discarded", "help wanted", "need changes", "pending review", "ready to merge",
            "resubmitted", "explanation needed", "Good task"];
            const labels = context.payload.pull_request.labels.map(label => label.name);
            const hasRequiredLabel = requiredLabels.some(label => labels.includes(label));

            if (hasRequiredLabel) {
              core.setOutput("label_present", "true");
              console.log("At least one required label is present.");
            } else {
              core.setOutput("label_present", "false");
              console.log("None of the required labels are present.");
            }

      - name: Fail if no required label is present
        if: steps.label_check.outputs.label_present == 'false'
        run: |
          echo "Pull request must have at least one of these labels: medium, expert, hard."
          exit 1